### ISSUE TITLE
It's not working!

### ISSUE THREAD

**Issue by shaypeleg1** [alondanoch/sparkdownload#1]
Hi,

I've tried running "npm start" but I'm getting this error:

                             \
                              \
                               \\
                                \\
                                 >\/7
                             _.-(6'  \
                            (=___._/` \
                                 )  \ |
                                /   / |
                               /    > /
                              j    < _\
                          _.-' :      ``.
                          \ r=._\        `.
                         <`\\_  \         .`-.
                          \ r-7  `-. ._  ' .  `\
                           \`,      `-.`7  7)   )
                            \/         \|  \'  / `-._
                                       ||    .'
cjr                                     \\  (
10mar02                                  >\  >
                                     ,.-' >.'
                                    <.'_.''
                                      <'

**Comment by alondanoch** [comment]
as expected 👅
